version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:stretch
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Update Packagelist
          command: |
            sudo apt-get update

      - run:
          name: Install Packages
          command: |
            sudo apt-get install \
                 apt-transport-https \
                 ca-certificates \
                 curl \
                 gnupg2 \
                 software-properties-common

      - run:
          name: Setup Repository
          command: |
            sudo add-apt-repository \
               "deb [arch=amd64] https://download.docker.com/linux/debian \
               $(lsb_release -cs) \
               stable"

      - run:
          name: Install Docker CE
          command: |
            set -x
            sudo apt-get update -y
            sudo apt-get install docker-ce -y --allow-unauthenticated

      - run:
          name: Build Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t goneproject/engine:$TAG ../docker/Dockerfile
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push goneproject/engine:$TAG
