---
jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: goneproject
    trigger: true
  - put: docker-image
    params:
      build: engine/.ci/docker

resources:
- name: goneproject
  type: git
  source:
    uri: https://github.com/GONEproject/engine.git
    branch: dev

- name: docker-image
  type: docker-image
  source:
    username: ((docker_hub.username))
    password: ((docker_hub.password))
    repository: ((docker_hub.repository))