---
# CONFIG FILE FOR CONCOURSE CI PIPELINE

# -------- CAUTION: DO NOT COMMIT!1 --------
#   THIS FILE IS NOT LISTED IN .gitignore!
#    USE default.yml AS AN EXAMPLE OR ADD 
#      IT TO .gitignore BEFORE PUSHING!
# -------- CAUTION: DO NOT COMMIT!1 --------

docker-hub:
  - username: example
    password: example
    repository: example

git:
  - private_key: MY_SECRET_PRIVATE_KEY